version: "3.1"
services:
  node-red:
    image: nodered/node-red:3.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./data:/data
    ports:
      - 1880:1880
